spring.application.name=bt_05
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShopBanHang;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=doantuan
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.autoconfigure.exclude=org.springframework.boot.session.jdbc.autoconfigure.JdbcSessionAutoConfiguration
server.error.whitelabel.enabled=false
